"""empty message

Revision ID: a0d6b098fc17
Revises: f841f56a4c6b
Create Date: 2022-04-08 01:28:49.300315

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'a0d6b098fc17'
down_revision = 'f841f56a4c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

        # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE types SET SCHEMA {SCHEMA};")




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('types')
    # ### end Alembic commands ###
