"""empty message

Revision ID: f841f56a4c6b
Revises: 7ff2823bf7b2
Create Date: 2022-04-08 01:28:07.778158

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'f841f56a4c6b'
down_revision = '7ff2823bf7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'type_id')
    # ### end Alembic commands ###
